version: '3.9'
services:
  app:
    ports:
      - "8080:80"
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: musicle_server
    volumes:
      - ./musicle:/source/musicle

  db_mysql:
    image: mysql:8
    container_name: musicle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicle
      MYSQL_USER: main
      MYSQL_PASSWORD: Admin
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3305:3306

volumes:
  mysql_volume:
    driver: local
